### ISSUE TITLE
bug: block node emits error when sending a response if the producer has closed the connection

### ISSUE THREAD

**Issue by mattp-swirldslabs** [hashgraph/hedera-block-node#179]
When running a test where `ghz` sends a large block and then disconnects, an error is thrown to the log like:
```
2024-09-16 09:38:36 Exception in thread "Thread-5" java.lang.RuntimeException: java.lang.IllegalStateException: Stream is already completed, no further calls are allowed
2024-09-16 09:38:36     at com.lmax.disruptor/com.lmax.disruptor.FatalExceptionHandler.handleEventException(FatalExceptionHandler.java:35)
2024-09-16 09:38:36     at com.lmax.disruptor/com.lmax.disruptor.BatchEventProcessor.handleEventException(BatchEventProcessor.java:254)
2024-09-16 09:38:36     at com.lmax.disruptor/com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:193)
2024-09-16 09:38:36     at com.lmax.disruptor/com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:122)
2024-09-16 09:38:36     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
2024-09-16 09:38:36     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2024-09-16 09:38:36     at java.base/java.lang.Thread.run(Thread.java:1583)
2024-09-16 09:38:36 Caused by: java.lang.IllegalStateException: Stream is already completed, no further calls are allowed
2024-09-16 09:38:36     at com.google.common@33.0.0-jre/com.google.common.base.Preconditions.checkState(Preconditions.java:512)
2024-09-16 09:38:36     at io.grpc.stub@1.65.1/io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:375)
2024-09-16 09:38:36     at com.hedera.block.server/com.hedera.block.server.producer.ProducerBlockItemObserver.onEvent(ProducerBlockItemObserver.java:207)
2024-09-16 09:38:36     at com.hedera.block.server/com.hedera.block.server.producer.ProducerBlockItemObserver.onEvent(ProducerBlockItemObserver.java:53)
2024-09-16 09:38:36     at com.lmax.disruptor/com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:167)
2024-09-16 09:38:36     ... 4 more
```
* I suspect this is because the ProducerBlockItemObserver attempts to send a block response but the producer (ghz) has already closed the connection.
* The grpc io interface for interacting with the underlying observer does not provide any status methods but we might be able to cast to the implementation class under the hood and check `isReady()` to check before invoking a response when the connection is already closed.
* It would be good to get rid of these errors since they pollute the logs and will become noisy in production.

**Comment by a-saksena** [comment]
@mattp-swirldslabs  to confirm if this is invalid now as we are not using grpc.io anymore.

**Comment by mattp-swirldslabs** [comment]
Helidon does not expose methods to check socket availability. We may have to live with this for now. There's some activity on [this ticket](https://github.com/helidon-io/helidon/issues/9496) so perhaps they will provide the ability to check availability before sending data.
