### ISSUE TITLE
Helidon doesn't resolve configuration properly

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-block-node#98]
Currently application is trying to use application.yaml for configuration, this results in error when trying to start the block-node.

```
WARNING: Configuration file application.yaml is on classpath, yet there is no parser configured for it
Exception in thread "main" io.helidon.config.MissingValueException: Requested value for configuration key 'blocknode.storage.root.path' is not present in the configuration.
	at io.helidon.config@4.0.11/io.helidon.config.MissingValueException.create(MissingValueException.java:44)
	at io.helidon.config@4.0.11/io.helidon.config.ConfigValue.lambda$get$0(ConfigValue.java:93)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.helidon.config@4.0.11/io.helidon.config.ConfigValue.get(ConfigValue.java:93)
	at com.hedera.block.server/com.hedera.block.server.persistence.storage.write.BlockAsDirWriterBuilder.<init>(BlockAsDirWriterBuilder.java:55)
	at com.hedera.block.server/com.hedera.block.server.persistence.storage.write.BlockAsDirWriterBuilder.newBuilder(BlockAsDirWriterBuilder.java:73)
	at com.hedera.block.server/com.hedera.block.server.Server.main(Server.java:72)
```

We'd need to fix the configurator to start using `app.properties` files for configuration variables.

**Comment by jsync-swirlds** [comment]
Note, If we prefer to keep the `yaml` format, we could also look into preventing Helidon from trying to read the file; and ensure platform SDK config _can_ read the file.
